language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - curl --version
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs
